SELECT SUBSTR(SALES_DATE, 1, 10)AS SALES_DATE,PRODUCT_ID,USER_ID,SALES_AMOUNT
FROM (
    SELECT SALES_DATE,PRODUCT_ID,USER_ID,SALES_AMOUNT FROM ONLINE_SALE
    UNION
    SELECT SALES_DATE,PRODUCT_ID,NULL,SALES_AMOUNT FROM OFFLINE_SALE
) A
WHERE SALES_DATE LIKE '2022-03%'
ORDER BY SALES_DATE, PRODUCT_ID, USER_ID